import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  header: {
    height: 100,
    backgroundColor: '#000',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 30,
  },
  botaoVoltar: {
    padding: 4,
  },
  logo: {
    color: '#fff',
    fontSize: 28,
    fontFamily: 'InriaSerif-Bold',
  },
  placeholderHeader: {
    width: 32,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  tituloTela: {
    fontSize: 26,
    color: '#000',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 10,
    fontFamily: 'InriaSerif-Regular', 
    lineHeight: 32,
  },
  botaoAvaliar: {
    backgroundColor: '#24E300',
    flexDirection: 'row',
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  textoBotaoAvaliar: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textVazio: {
    textAlign: 'center',
    color: '#999',
    marginTop: 40,
    fontSize: 15,
  },
  card: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eee',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  imagemProduto: {
    width: 80,
    height: 80,
    borderRadius: 6,
    backgroundColor: '#f9f9f9',
  },
  infoContainer: {
    flex: 1,
    paddingHorizontal: 12,
  },
  nomeUsuario: {
    fontSize: 14,
    color: '#000',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  estrelasContainer: {
    flexDirection: 'row',
    gap: 2,
    marginBottom: 6,
  },
  comentarioText: {
    fontSize: 13,
    color: '#444',
    lineHeight: 18,
  },
  botaoDenunciar: {
    backgroundColor: '#ff0000',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    height: 36,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  textoBotaoDenunciar: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#fff',
    width: '100%',
    maxHeight: '85%',
    borderRadius: 12,
    padding: 20,
    elevation: 5,
  },
  modalTitulo: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    color: '#000',
  },
  modalForm: {
    gap: 14,
  },
  modalInputGroup: {
    width: '100%',
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 15,
    color: '#000',
  },
  modalInputArea: {
    height: 80,
    textAlignVertical: 'top',
    paddingVertical: 8,
  },
  seletorEstrelas: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginVertical: 10,
  },
  imageUploadArea: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#ccc',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
    overflow: 'hidden',
    marginVertical: 5,
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  imageUploadPlaceholder: {
    alignItems: 'center',
    gap: 6,
  },
  textPlaceholderImg: {
    color: '#888',
    fontSize: 13,
    fontWeight: '500',
  },
  modalBotoes: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    gap: 10,
  },
  modalBotaoCancelar: {
    flex: 1,
    height: 46,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTextoCancelar: {
    color: '#000',
    fontWeight: 'bold',
  },
  modalBotaoSalvar: {
    flex: 1,
    height: 46,
    backgroundColor: '#000',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTextoSalvar: {
    color: '#fff',
    fontWeight: 'bold',
  },
  fundoModal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  conteudoModal: {
    backgroundColor: '#fff',
    width: '100%',
    borderRadius: 14,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 10,
  },
  tituloModal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
  },
  labelInput: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
    marginTop: 10,
  },
  inputMotivo: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 44,
    color: '#000',
    fontSize: 15,
    backgroundColor: '#fafafa',
  },
  inputDescricao: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    height: 100,
    color: '#000',
    fontSize: 15,
    backgroundColor: '#fafafa',
  },
  botoesModalContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 24,
  },
  botaoCancelarModal: {
    paddingHorizontal: 16,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    backgroundColor: '#eee',
  },
  textoCancelarModal: {
    color: '#333',
    fontWeight: '600',
  },
  botaoConfirmarModal: {
    paddingHorizontal: 20,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    backgroundColor: '#ff0055',
  },
  textoConfirmarModal: {
    color: '#fff',
    fontWeight: 'bold',
  },
});